### ISSUE TITLE
Bug: EuclideanEmbeddedSubmanifold class not present in pymanopt.manifolds.manifold

### ISSUE THREAD

**Issue by SalvishGoomanee** [geomstats/geomstats#1624]
### Describe the bug

In the `examples` folder, upon running `python geomstats_in_pymanopt.py`, I got the following error: 

```
Traceback (most recent call last):
  File "geomstats_in_pymanopt.py", line 14, in <module>
    from pymanopt.manifolds.manifold import `EuclideanEmbeddedSubmanifold`
ImportError: cannot import name 'EuclideanEmbeddedSubmanifold' from 'pymanopt.manifolds.manifold' (/Users/salvishgoomanee/Desktop/PycharmProjects/research_notebooks/venv-research/lib/python3.8/site-packages/pymanopt/manifolds/manifold.py)
```

The `EuclideanEmbeddedSubmanifold` class is not present in `pymanopt.manifolds.manifold` and cannot be inherited from. I am not sure how to proceed. I believe I must be missing something. 

### Steps/Code to Reproduce

I ran `python geomstats_in_pymanopt.py` after having cloned the Geomstats package in my current directory. 

### Expected Behaviour

Expecting results for the following: 

  ```
  logging.info(
        "l2-norm of dominant eigenvector: %s", gs.linalg.norm(dominant_eigenvector)
    )
    logging.info(
        "l2-norm of dominant eigenvector estimate: %s",
        gs.linalg.norm(dominant_eigenvector_estimate),
    )
    error_norm = gs.linalg.norm(dominant_eigenvector - dominant_eigenvector_estimate)
    logging.info("l2-norm of difference vector: %s", error_norm)
    logging.info("solution found: %s", gs.isclose(error_norm, 0.0, atol=1e-3))
```

### Actual Behaviour

Actual result is: 

```
Traceback (most recent call last):
  File "geomstats_in_pymanopt.py", line 14, in <module>
    from pymanopt.manifolds.manifold import EuclideanEmbeddedSubmanifold
ImportError: cannot import name 'EuclideanEmbeddedSubmanifold' from 'pymanopt.manifolds.manifold' (/Users/salvishgoomanee/Desktop/PycharmProjects/research_notebooks/venv-research/lib/python3.8/site-packages/pymanopt/manifolds/manifold.py)
```

### Your environment

```shell
Geomstats version: 2.5.0
OS: Mac os
```

**Comment by lpereira95** [comment]
Thanks for pointing this out @SalvishGoomanee!

This is a versioning problem. This example was last updated in May 2020. Meanwhile, both `geomstats` and `pymanopt` have evolved.

I believe you can make it work with `pymanopt` version 0.2.5 or 1.0.0. I can help you out making it work with current versions if you need it (I'll probably update the example soon).
